name: build

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: zulu

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: build
      run: ./gradlew build

    - name: archive vgo test results
      uses: actions/upload-artifact@v4
      with:
        name: vgo_test_results
        path: vgo/build/reports/tests/test/

    - name: archive vgo core test results
      uses: actions/upload-artifact@v4
      with:
        name: vgo_core_test_results
        path: vgo-core/build/reports/tests/test/

    - name: release binary
      run: ./gradlew binary

    - name: archive vgo
      uses: actions/upload-artifact@v4
      with:
        name: vgo
        path: vgo/build/libs/vgo
